### ISSUE TITLE
Wrong localization by moment.js

### ISSUE THREAD

**Issue by axewater** [gsabater/backlog.rip#27]
OS: Windows 11
Regional settings: Country Netherlands, Language Dutch
Browser: Edge set to English language.
Issue: Most of the site is in the English language, but on the journal page there are bits in a latin language.

Journal
Abril
16 de abril de 2024
Event recorded
This is your first entry in the journal. Welcome!
Entry added 16 de abril de 2024 8:42:24

**Comment by gsabater** [comment]
Hello @axewater 
There’s definitely a mistake I made in the dates plugin library by initializing it only in spanish

**Comment by gsabater** [comment]
Hello @axewater 
This issue is now solved and pushed to production.
In the future i would like to translate the site and allow users to select their language for dates, but for now, everything will be in english.

-- 
Fixed in release 0.15
Complete changelog in https://backlog.rip/changelog
